### ISSUE TITLE
IP wrangler general description

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/ip-wrangler#1]
General description is missing. It should explain what `ipt-wrangler` does, what are the limitations, etc.

PS. Why `ipt-wrangler` not `ip-wrangler`

**Comment by pasuder** [comment]
In file [README.md](https://github.com/dice-cyfronet/ipt-wrangler/blob/master/README.md)? Like [README.md](https://github.com/dice-cyfronet/redirus/blob/master/README.md) from [Redirus](https://github.com/dice-cyfronet/redirus)?

**Comment by pasuder** [comment]
Name changed from `ipt-wrangler` to `ip-wrangler`.

**Comment by mkasztelnik** [comment]
Yes something like this. Of course it also can be longer than Redirus description :smile:

**Comment by pasuder** [comment]
See #10

**Comment by mkasztelnik** [comment]
Hmm I see usage description but not general description

**Comment by pasuder** [comment]
![zrzut ekranu z 2015-02-03 11 12 08](https://cloud.githubusercontent.com/assets/3436085/6018240/8dd1ed4a-ab95-11e4-955c-5bdddc2bc0a8.png)
Is it not a general description?

**Comment by pasuder** [comment]
May I need to write that _ip-wrangler_ uses port pool in db and rotate port redirections and other hidden features :smiley:

**Comment by mkasztelnik** [comment]
I looks like usage description no general description what ip-wrangler does

**Comment by pasuder** [comment]
Will we closed it if README.md in #4 is proper?

**Comment by mkasztelnik** [comment]
yeap
