### ISSUE TITLE
Pack ipt-wrangler into gem and publish it on rubygems

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/ip-wrangler#2]
It would be nice to pack it into a gem with dedicated executables. An example how it can be done can be found in https://github.com/dice-cyfronet/redirus

**Comment by pasuder** [comment]
Working in #4

**Comment by pasuder** [comment]
I will publish gem at rubygems.org and tag commit with `v0.1.0` after closing #4.

**Comment by mkasztelnik** [comment]
great

**Comment by pasuder** [comment]
Done with #4 Published as https://rubygems.org/gems/ip-wrangler
