### ISSUE TITLE
ip-wrangler code refactor

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/ip-wrangler#8]
Inside `ip-wrangler` code there are many code duplication. Take a look for example [here](https://github.com/dice-cyfronet/ip-wrangler/blob/master/src/ipt_main.rb#L46-l50) and [here](https://github.com/dice-cyfronet/ip-wrangler/blob/master/src/ipt_main.rb#L58-l62) (map function) or [here](https://github.com/dice-cyfronet/ip-wrangler/blob/master/src/ipt_main.rb#L181-l191) and [here](https://github.com/dice-cyfronet/ip-wrangler/blob/master/src/ipt_main.rb#L215-225). 

Parts which share similar behaviour should be extracted into one method and used in many places.

**Comment by pasuder** [comment]
@mkasztelnik thank you. I have enabled [CodeClimate](https://codeclimate.com/github/dice-cyfronet/ip-wrangler) for this project, so code quality is monitored :smiley:

**Comment by pasuder** [comment]
Working on it in #4

**Comment by mkasztelnik** [comment]
@paoolo in the scope of #4 please only migrate into gem structure. If you will do a lot o refactoring there it will be hard to do good code review.

IMHO it is better to have many small PR than one big one.

**Comment by pasuder** [comment]
True. OK.

**Comment by pasuder** [comment]
I guess that could be closed after so long inactivity.
